/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1', // Main brand color
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
        },
        "inverse-on-surface": "#eff1f4",
        "primary-fixed": "#dfec60",
        "on-secondary-fixed-variant": "#004495",
        "primary-container": "#717b00",
        "tertiary-fixed": "#d7e2ff",
        "on-tertiary-container": "#fefcff",
        "tertiary": "#4f5c77",
        "surface-container": "#eceef1",
        "surface-container-high": "#e6e8eb",
        "surface": "#f7f9fc",
        "background": "#f7f9fc",
        "secondary-fixed": "#d8e2ff",
        "on-primary-container": "#feffdb",
        "on-error-container": "#93000a",
        "on-secondary-container": "#fefcff",
        "outline": "#727785",
        "on-primary": "#ffffff",
        "on-surface": "#191c1e",
        "surface-container-low": "#f2f4f7",
        "surface-container-highest": "#e0e3e6",
        "on-tertiary-fixed": "#0d1b33",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f7f9fc",
        "surface-dim": "#d8dadd",
        "tertiary-fixed-dim": "#b9c7e6",
        "on-secondary-fixed": "#001a42",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#444b00",
        "inverse-primary": "#c2cf47",
        "secondary": "#0058bd",
        "inverse-surface": "#2d3133",
        "secondary-fixed-dim": "#adc6ff",
        "error": "#ba1a1a",
        "on-primary-fixed": "#1a1d00",
        "on-surface-variant": "#424754",
        "primary-fixed-dim": "#c2cf47",
        "secondary-container": "#1e70e4",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e0e3e6",
        "outline-variant": "#c2c6d6",
        "primary": "#596100",
        "tertiary-container": "#677591",
        "surface-tint": "#5b6300",
        "on-background": "#191c1e",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#394761"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'], // Keep this as default
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
